CI check code style
JDRaftKeeper/RaftKeeper pull request #16
Opened 2023-03-20 07:05 UTC by nicelulu

Add check code style CI workflows.

2023-03-20 07:37 UTC, JackyWoo commented
if check fails, we should print error info.

2023-03-20 07:39 UTC, JackyWoo commented
Check failed, but shows successful.
```
/home/runner/work/RaftKeeper/RaftKeeper/src/Service/SocketReactor.cpp:291:	}
ErrorCode DECIMAL_OVERFLOW is defined but not used in file /home/runner/work/RaftKeeper/RaftKeeper/src/Common/Field.cpp
```

2023-03-20 10:50 UTC, nicelulu commented
> Check failed, but shows successful.

Fixed see https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/4467329352/jobs/7846645660

2023-03-21 04:58 UTC, JackyWoo requested changes

2023-03-22 04:49 UTC, JackyWoo requested changes

2023-03-22 04:49 UTC, JackyWoo commented on utils/check-style/check-whitespaces
> +    while read i; do $ROOT_PATH/utils/check-style/double-whitespaces.pl < $i || echo -e "^ File $i contains double whitespaces\n"; done
need a blank line

2023-03-22 04:54 UTC, JackyWoo requested changes

2023-03-22 04:54 UTC, JackyWoo commented on .github/workflows/check-style.yml
> +on:
should fix the warning

2023-03-22 04:54 UTC, JackyWoo commented on tests/ci/code_style_check.py
> +    if state == "failure" or state == "exception":
seems not display the error message

2023-03-22 05:11 UTC, merged