Feat/max min session time out
JDRaftKeeper/RaftKeeper pull request #38
Opened 2023-04-04 09:56 UTC by Hooollin

### Which issues of this PR fixes ：

This PR try to fix #22

### Change log

Add maximum session timeout ms and minimum session timeout ms for client connection.

2023-04-06 02:54 UTC, Hooollin commented
What if user sets minimum session timeout to be greater than the maximum timeout in the `config.xml`? Some checks should be performed and corresponding logs should be added as well.

2023-04-06 03:26 UTC, JackyWoo commented
There are 3 timeout durations in the system and their size should be in the order of operation timeout < min session timeout < max session timeout.

If out of order we should log a warning and set a default value base on max session timeout (t)
1. min session timeout = 1/2 t
2. operation timeout = 1/4 t

@Hooollin what do you think?

2023-04-06 07:17 UTC, Hooollin commented
> 

It's a good idea. But 

> There are 3 timeout durations in the system and their size should be in the order of operation timeout < min session timeout < max session timeout.
> 
> If out of order we should log a warning and set a default value base on max session timeout (t)
> 
> 1. min session timeout = 1/2 t
> 2. operation timeout = 1/4 t
> 
> @Hooollin what do you think?

It's a good idea. Considering t might be a relative large number, we can set `min_session_timeout_ms` to 1/10 t and `operation_timeout_ms` to 1/20 t. If `max_session_timeout_ms` is set to 40s, then we have `min_session_timeout_ms` to be 4s and `operation_timeout_ms` to be 2s. Even if all the three values are in order, I think `minimum_session_timeout_ms` should at least be 2 times the `operation_timeout_ms` to make sure the session is alive before operation finishes.

And Maybe we can set up a `tickTime` as the basic unit, set `min_session_timeout_ms` to 2 times `tickTime` and set `max_session_timeout_ms` to 20 times `tickTime` just like what ZooKeeper have done.

2023-04-12 10:32 UTC, nicelulu commented
You can refer to the operation timeout algorithm of the ```KazooClient```: ```negotiated_session_timeout * 2.0 / 3.0```.
ClickHouse ZooKeeper Client default operation timeout is 10000ms, default session timeout is 30000ms.

I think a slightly larger default timeout would be better. Because our snapshot will take a long time.

2023-04-27 03:45 UTC, Hooollin commented
> You can refer to the operation timeout algorithm of the `KazooClient`: `negotiated_session_timeout * 2.0 / 3.0`. ClickHouse ZooKeeper Client default operation timeout is 10000ms, default session timeout is 30000ms.
> 
> I think a slightly larger default timeout would be better. Because our snapshot will take a long time.

I leave `operation_timeout_ms` as it is, only do check on the value of `minimum_session_timeout_ms` and `maximum_session_timeout_ms`. Please review my latest commit.

2023-04-27 05:13 UTC, JackyWoo requested changes

2023-04-27 05:19 UTC, JackyWoo commented on src/Service/Settings.cpp
> +SettingsPtr Settings::loadFromConfig(const Poco::Util::AbstractConfiguration & config, bool standalone_keeper_, Poco::Logger * log)
It is better to create a logger in `Settings .loadFromConfig` and name it to 'Settings'

2023-04-27 05:26 UTC, JackyWoo requested changes

2023-04-27 05:26 UTC, JackyWoo commented on tests/integration/test_session_fake_client/test.py
> +def test_session_max_min_session_timeout(started_cluster):
Could you make the test run in a shor time?

2023-04-28 03:18 UTC, Hooollin commented on tests/integration/helpers/xml_processor.py
> +import os
Manipulating xml file such as adding new tag, renaming tag, etc. It helps me with substitute tag name in this pr, thus I think it might be helpful.

2023-05-15 03:20 UTC, JackyWoo requested changes

2023-05-15 03:20 UTC, JackyWoo commented on src/Service/KeeperDispatcher.cpp
> +    LOG_DEBUG(log, "Initializing dispatcher");
We'd better use info

2023-05-15 03:21 UTC, JackyWoo commented
Generally LGTM

2023-05-15 08:57 UTC, Hooollin commented
> Found a test failure https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/4967136485/jobs/8888956494?pr=38 =========================== short test summary info ============================ FAILED test_session_fake_client/test.py::test_session_max_min_session_timeout ============ 1 failed, 81 passed, 2 warnings in 1057.00s (0:17:37) =============

I'll check it ASAP.

2023-05-15 15:14 UTC, Hooollin commented
> Found a test failure https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/4967136485/jobs/8888956494?pr=38 =========================== short test summary info ============================ FAILED test_session_fake_client/test.py::test_session_max_min_session_timeout ============ 1 failed, 81 passed, 2 warnings in 1057.00s (0:17:37) =============

I run it several times on my machine, no failure is found. I suppose it's not a reproducible error caused by CI(I didn't look into that error message so I'm not sure what kind of failure it is). I've correct the log level and pushed a new commit, let's it'll fail again or not.

> > Found a test failure https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/4967136485/jobs/8888956494?pr=38 =========================== short test summary info ============================ FAILED test_session_fake_client/test.py::test_session_max_min_session_timeout ============ 1 failed, 81 passed, 2 warnings in 1057.00s (0:17:37) =============
> 
> I run it several times on my machine, no failure is found. I suppose it's not a reproducible error caused by CI(Connection Refused). I've correct the log level and pushed a new commit, let's it'll fail again or not.



> > Found a test failure https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/4967136485/jobs/8888956494?pr=38 =========================== short test summary info ============================ FAILED test_session_fake_client/test.py::test_session_max_min_session_timeout ============ 1 failed, 81 passed, 2 warnings in 1057.00s (0:17:37) =============
> 
> I run it several times on my machine, no failure is found. I suppose it's not a reproducible error caused by CI(Connection Refused). I've correct the log level and pushed a new commit, let's it'll fail again or not.

Maybe it takes longer to start raftkeeper in CI environment. I've update max session timeout in `config.xml` to avoid restart raftkeeper.

2023-05-15 15:17 UTC, Hooollin commented
Should I squash the commit history into one?

2023-05-16 04:43 UTC, merged